In [98]:
import numpy as np
import pandas as pd

In [105]:
class multiple_regression(object):
    def __init__(self,eta=0.1):
        self.eta = eta
        
    def fit(self,X,y):
        self.weight = np.random.RandomState(1).normal(loc=0,scale=0.1,size = X.shape[1]+1)
        self.m = X.shape[0]
        self.n = X.shape[1]
        self.cost = 0
        self.costl = []
        self.dif = sum(np.dot(X,self.weight[1:])+self.weight[0]-y)
        
        for xi,target in zip(X,y):
            self.cost = sum((np.dot(X,self.weight[1:])+self.weight[0]-y)**2)
            self.costl.append(self.cost)
            self.a = self.weight[0] - self.eta*self.dif/self.m
            self.b = self.weight[1:] - ((self.eta*self.dif/self.m)*xi)
            self.weight[0] = self.a
            self.weight[1:] = self.b
            
        return self
            
            
            
            
        

In [106]:
y = df['HousePrice']

In [164]:
lr = multiple_regression(eta = 0.000001)

In [165]:
lr.fit(X,y)

In [166]:
lr.weight

array([ 15.78844158, 508.98362556, 301.26079341])

In [167]:
lr.costl

[3202082908536.6357,
 3197070886232.5654,
 3192037702250.4277,
 3186944095692.2324,
 3177851682920.112,
 3168759498846.958,
 3160339784960.6606,
 3154792664930.769,
 3151407271347.9478,
 3147373496053.9253,
 3142150025071.7686,
 3136855049183.53,
 3129400596216.0586,
 3123972670314.8135,
 3116491911422.9424,
 3109132028011.7217,
 3105483074510.307,
 3097280757168.318,
 3092288358331.928,
 3080638080218.966,
 3072531810284.9736,
 3066765173304.947,
 3061528556420.49,
 3055251090832.343,
 3051700352069.2417,
 3045223968558.4736,
 3041134764102.812,
 3036449613445.7085,
 3031880602373.8135,
 3027822437235.641,
 3024842807262.327,
 3020759740919.489,
 3017692213527.8228,
 3012273865725.6714,
 3008613765798.7056,
 3003679334485.9663,
 2999270021879.288,
 2994869241285.6143,
 2988043596253.9917,
 2985065800002.694,
 2977051875743.967,
 2973340762461.489,
 2969534556130.4717,
 2963157203942.576,
 2956275109254.953,
 2950633036816.4946,
 2946212225058.057,
 2940953606502.1787,
 2937855994224.6

In [168]:
lr.costl

[3202082908536.6357,
 3197070886232.5654,
 3192037702250.4277,
 3186944095692.2324,
 3177851682920.112,
 3168759498846.958,
 3160339784960.6606,
 3154792664930.769,
 3151407271347.9478,
 3147373496053.9253,
 3142150025071.7686,
 3136855049183.53,
 3129400596216.0586,
 3123972670314.8135,
 3116491911422.9424,
 3109132028011.7217,
 3105483074510.307,
 3097280757168.318,
 3092288358331.928,
 3080638080218.966,
 3072531810284.9736,
 3066765173304.947,
 3061528556420.49,
 3055251090832.343,
 3051700352069.2417,
 3045223968558.4736,
 3041134764102.812,
 3036449613445.7085,
 3031880602373.8135,
 3027822437235.641,
 3024842807262.327,
 3020759740919.489,
 3017692213527.8228,
 3012273865725.6714,
 3008613765798.7056,
 3003679334485.9663,
 2999270021879.288,
 2994869241285.6143,
 2988043596253.9917,
 2985065800002.694,
 2977051875743.967,
 2973340762461.489,
 2969534556130.4717,
 2963157203942.576,
 2956275109254.953,
 2950633036816.4946,
 2946212225058.057,
 2940953606502.1787,
 2937855994224.6

In [115]:
import sklearn

In [117]:
from sklearn.preprocessing import StandardScaler

In [118]:
X = StandardScaler().fit_transform(X)

In [124]:
from sklearn.linear_model import LinearRegression

In [148]:
l = LinearRegression()

In [149]:
l.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [151]:
l.coef_

array([-523.24023572,  887.4716627 ])

In [141]:
X = df[['CrimeRate','MilesPhila']].values
y = df['HousePrice']

In [176]:
sum((l.predict(X)-y)**2)

683746039277.078

In [177]:
df = pd.read_csv('data.csv')

In [188]:
df

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [182]:
X = df[['bedrooms','bathrooms','sqft_lot']].values

In [180]:
y = df['price']

In [185]:
l.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

array([1.90990432e+04, 2.22058162e+05, 2.36398955e-01])

In [190]:
sum((l.predict(X)-y)**2)

1304310430710585.5

In [241]:
lr = multiple_regression(eta=0.00000000000023)
lr.fit(X,y)

In [242]:
lr.costl[-1]

2646855318027943.0